// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateGroupRequest struct {
	CreateGroupName        string `json:"create_group_name"`
	CreateGroupDescription string `json:"create_group_description"`
	CreateGroupOwnerName   string `json:"create_group_owner_name"`
}

type CreateGroupResponse struct {
	CreateMessage string `json:"create_message"`
}

type DeleteGroupRequest struct {
	DeleteGroupName string `json:"delete_group_name"`
	UserName        string `json:"user_name"`
}

type DeleteGroupResponse struct {
	DeleteMessage string `json:"delete_message"`
}

type GetMemberRequest struct {
	RequestUserID string `json:"request_user_id"`
	GroupID       string `json:"group_id"`
}

type GetMemberResponse struct {
	Members []string `json:"members"`
}

type JoinGroupRequest struct {
	JoinGroupName string `json:"join_group_name"`
	JoinerName    string `json:"joiner_name"`
}

type JoinGroupResponse struct {
	JoinMessage string `json:"join_message"`
}
