services:
#   nginx:
#     image: nginx:alpine
#     container_name: chatLion-nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./static:/app/static:ro
#       - ./resources:/app/resources:ro
#       - ./logs/nginx:/var/log/nginx
#     depends_on:
#       - chat-lion
#     networks:
#       - kafka-network
#     restart: unless-stopped

  # mysql:
  #   image: mysql:8.0
  #   container_name: chatLion-mysql
  #   ports:
  #       - "3307:3306"
  #   volumes:
  #       - mysql-data:/var/lib/mysql
  #       - ./scripts/chat.sql:/docker-entrypoint-initdb.d/chat.sql
  #   networks:
  #       - kafka-network
  #   environment:
  #       MYSQL_ROOT_PASSWORD: 0220059cyCY  # 高复杂度密码
  #       MYSQL_DATABASE: chat
  #       TZ: Asia/Shanghai
  #   healthcheck:    # 增加健康检查
  #       test: mysqladmin ping -uroot -p$${MYSQL_ROOT_PASSWORD}
  #       interval: 5s
  #       timeout: 10s
  #       retries: 10

  redis:
    image: redis:6.2-alpine
    container_name: chatLion-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: chatLion-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: chatLion-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      # 日志配置
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      # 性能优化
      KAFKA_NUM_NETWORK_THREADS: 8
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      # 支持大文件传输 - 设置最大消息大小为 10MB
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # 初始化脚本容器
  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    container_name: chatLion-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    command: |
      bash -c '
      echo "等待Kafka启动..."
      sleep 10
      
      echo "创建聊天消息主题..."
      kafka-topics --create --if-not-exists --topic chat-messages --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1
      
      echo "创建用户事件主题..."
      kafka-topics --create --if-not-exists --topic user-events --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1
      
      echo "创建群组消息主题..."
      kafka-topics --create --if-not-exists --topic group-messages --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1
      
      echo "列出所有主题:"
      kafka-topics --list --bootstrap-server kafka:29092
      
      echo "主题创建完成!"
      '
    networks:
      - kafka-network

  chat-lion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatLion-chat-lion
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      zookeeper:
        condition: service_started
    ports:
      - "9922:9922"
    environment:
      - CONFIG_PATH=./config/config.prod.yaml
      - GIN_MODE=release
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    networks:
      - kafka-network
    restart: unless-stopped


volumes:
  zookeeper-data:
    driver: local
  zookeeper-logs:
    driver: local
  kafka-data:
    driver: local
  redis-data:
    driver: local
  chat-lion-data:
    driver: local
  mysql-data:
    driver: local


networks:
  kafka-network:
    driver: bridge