// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: user.proto

package server

import (
	"context"

	"chatLion/rpc/user/internal/logic"
	"chatLion/rpc/user/internal/svc"
	"chatLion/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) ModifyUser(ctx context.Context, in *user.ModifyUserRequest) (*user.ModifyUserResponse, error) {
	l := logic.NewModifyUserLogic(ctx, s.svcCtx)
	return l.ModifyUser(in)
}
