// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ModifyUserRequest struct {
	Email       string `json:"email"`
	NewUserName string `json:"new_user_name"`
}

type ModifyUserResponse struct {
	ModifyMessage string `json:"modify_message"`
}
