// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: friend.proto

package server

import (
	"context"

	"chatLion/rpc/friend/friend"
	"chatLion/rpc/friend/internal/logic"
	"chatLion/rpc/friend/internal/svc"
)

type FriendServer struct {
	svcCtx *svc.ServiceContext
	friend.UnimplementedFriendServer
}

func NewFriendServer(svcCtx *svc.ServiceContext) *FriendServer {
	return &FriendServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendServer) AddFriend(ctx context.Context, in *friend.AddFriendRequest) (*friend.AddFriendResponse, error) {
	l := logic.NewAddFriendLogic(ctx, s.svcCtx)
	return l.AddFriend(in)
}

func (s *FriendServer) DeleteFriend(ctx context.Context, in *friend.DeleteFriendRequest) (*friend.DeleteFriendResponse, error) {
	l := logic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

func (s *FriendServer) GetFriends(ctx context.Context, in *friend.GetFriendsListRequest) (*friend.GetFriendsListResponse, error) {
	l := logic.NewGetFriendsLogic(ctx, s.svcCtx)
	return l.GetFriends(in)
}
