// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type WebSocketRequest struct {
	JWT  string `json"jwt"`
	UUID string `json"uuid"`
}

type WebSocketResponse struct {
	Message string `json"message"`
}
