// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"chatLion/api/group/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/group/DeleteGroupByGroupID",
				Handler: DeleteGroupByGroupIDHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/createGroup",
				Handler: CreateGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/group/getMembersByGroupID",
				Handler: GetMembersByGroupIDHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/joinGroup",
				Handler: JoinGroupHandler(serverCtx),
			},
		},
	)
}
