// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AddFriendRequest struct {
	AdderEmail  string `json:"adder_email"`
	TargetEmail string `json:"target_email"`
	Content     string `json:"contnt"`
}

type AddFriendResponse struct {
	AddMessage string `json:"add_message"`
}
