// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/protocol/message.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Avatar       string `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FromUsername string `protobuf:"bytes,2,opt,name=fromUsername,proto3" json:"fromUsername,omitempty"`
	From         string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To           string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Content      string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ContentType  int32  `protobuf:"varint,6,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Type         string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	MessageType  int32  `protobuf:"varint,8,opt,name=messageType,proto3" json:"messageType,omitempty"`
	Url          string `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	FileSuffix   string `protobuf:"bytes,10,opt,name=fileSuffix,proto3" json:"fileSuffix,omitempty"`
	File         []byte `protobuf:"bytes,11,opt,name=file,proto3" json:"file,omitempty"`
	// 消息分片相关字段
	MessageId            string   `protobuf:"bytes,12,opt,name=messageId,proto3" json:"messageId,omitempty"`
	IsFragmented         bool     `protobuf:"varint,13,opt,name=isFragmented,proto3" json:"isFragmented,omitempty"`
	FragmentIndex        int32    `protobuf:"varint,14,opt,name=fragmentIndex,proto3" json:"fragmentIndex,omitempty"`
	TotalFragments       int32    `protobuf:"varint,15,opt,name=totalFragments,proto3" json:"totalFragments,omitempty"`
	Timestamp            int64    `protobuf:"varint,16,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Checksum             string   `protobuf:"bytes,17,opt,name=checksum,proto3" json:"checksum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc7b5b78212a3e3f, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Message) GetFromUsername() string {
	if m != nil {
		return m.FromUsername
	}
	return ""
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetContentType() int32 {
	if m != nil {
		return m.ContentType
	}
	return 0
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *Message) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Message) GetFileSuffix() string {
	if m != nil {
		return m.FileSuffix
	}
	return ""
}

func (m *Message) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Message) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Message) GetIsFragmented() bool {
	if m != nil {
		return m.IsFragmented
	}
	return false
}

func (m *Message) GetFragmentIndex() int32 {
	if m != nil {
		return m.FragmentIndex
	}
	return 0
}

func (m *Message) GetTotalFragments() int32 {
	if m != nil {
		return m.TotalFragments
	}
	return 0
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "protocol.Message")
}

func init() { proto.RegisterFile("pkg/protocol/message.proto", fileDescriptor_fc7b5b78212a3e3f) }

var fileDescriptor_fc7b5b78212a3e3f = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xdd, 0x4e, 0xc2, 0x40,
	0x10, 0x85, 0x53, 0xca, 0x4f, 0x19, 0x7e, 0xc4, 0xb9, 0x30, 0x13, 0x62, 0x4c, 0x43, 0x8c, 0xe9,
	0x95, 0x5c, 0xf8, 0x0e, 0x26, 0x5c, 0x78, 0x53, 0xf5, 0x01, 0xd6, 0x32, 0xc5, 0x86, 0x6e, 0xb7,
	0xe9, 0x2e, 0x06, 0x9f, 0xd9, 0x97, 0x30, 0x3b, 0x14, 0x01, 0xef, 0xce, 0xf9, 0x4e, 0xcf, 0x64,
	0xa6, 0x0b, 0xf3, 0x7a, 0xbb, 0x59, 0xd6, 0x8d, 0x71, 0x26, 0x33, 0xe5, 0x52, 0xb3, 0xb5, 0x6a,
	0xc3, 0x8f, 0x02, 0x30, 0x3a, 0xf2, 0xc5, 0x4f, 0x08, 0x83, 0x97, 0x43, 0x86, 0x37, 0xd0, 0x57,
	0x5f, 0xca, 0xa9, 0x86, 0x82, 0x38, 0x48, 0x86, 0x69, 0xeb, 0x70, 0x01, 0xe3, 0xbc, 0x31, 0xfa,
	0xdd, 0x72, 0x53, 0x29, 0xcd, 0xd4, 0x91, 0xf4, 0x82, 0x21, 0x42, 0xd7, 0x7b, 0x0a, 0x25, 0x13,
	0x8d, 0x53, 0xe8, 0x38, 0x43, 0x5d, 0x21, 0x1d, 0x67, 0x90, 0x60, 0x90, 0x99, 0xca, 0x71, 0xe5,
	0xa8, 0x27, 0xf0, 0x68, 0x31, 0x86, 0x51, 0x2b, 0xdf, 0xbe, 0x6b, 0xa6, 0x7e, 0x1c, 0x24, 0xbd,
	0xf4, 0x1c, 0xf9, 0xf9, 0xce, 0x47, 0x83, 0xc3, 0x7c, 0xaf, 0x7d, 0xab, 0x3d, 0x4b, 0x5a, 0xd1,
	0xa1, 0x75, 0x86, 0x70, 0x06, 0xe1, 0xae, 0x29, 0x69, 0x28, 0x25, 0x2f, 0xf1, 0x0e, 0x20, 0x2f,
	0x4a, 0x7e, 0xdd, 0xe5, 0x79, 0xb1, 0x27, 0x90, 0xe0, 0x8c, 0xc8, 0x1d, 0x45, 0xc9, 0x34, 0x8a,
	0x83, 0x64, 0x9c, 0x8a, 0xc6, 0x5b, 0x18, 0xb6, 0x43, 0x57, 0x6b, 0x1a, 0x4b, 0xe5, 0x04, 0xfc,
	0xdf, 0x29, 0xec, 0x73, 0xa3, 0x36, 0x9a, 0x2b, 0xc7, 0x6b, 0x9a, 0xc4, 0x41, 0x12, 0xa5, 0x17,
	0x0c, 0xef, 0x61, 0x92, 0xb7, 0x6e, 0x55, 0xad, 0x79, 0x4f, 0x53, 0xd9, 0xf5, 0x12, 0xe2, 0x03,
	0x4c, 0x9d, 0x71, 0xaa, 0x3c, 0x16, 0x2d, 0x5d, 0xc9, 0x67, 0xff, 0xa8, 0xdf, 0xc7, 0x15, 0x9a,
	0xad, 0x53, 0xba, 0xa6, 0x59, 0x1c, 0x24, 0x61, 0x7a, 0x02, 0x38, 0x87, 0x28, 0xfb, 0xe4, 0x6c,
	0x6b, 0x77, 0x9a, 0xae, 0x65, 0xd9, 0x3f, 0xff, 0xd1, 0x97, 0x77, 0x7f, 0xfa, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x5b, 0xea, 0x7f, 0x57, 0x1c, 0x02, 0x00, 0x00,
}
