// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: friend.proto

package friendclient

import (
	"context"

	"chatLion/rpc/friend/friend"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFriendRequest     = friend.AddFriendRequest
	AddFriendResponse    = friend.AddFriendResponse
	DeleteFriendRequest  = friend.DeleteFriendRequest
	DeleteFriendResponse = friend.DeleteFriendResponse

	Friend interface {
		AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
		DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error)
	}

	defaultFriend struct {
		cli zrpc.Client
	}
)

func NewFriend(cli zrpc.Client) Friend {
	return &defaultFriend{
		cli: cli,
	}
}

func (m *defaultFriend) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.AddFriend(ctx, in, opts...)
}

func (m *defaultFriend) DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.DeleteFriend(ctx, in, opts...)
}
