MySQL:
  dsn: "root:password@tcp(127.0.0.1:3306)/chat?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

JWT:
  api_secret: "chat-api-secret"
  expires_time: 86400
  issuer: "chat-lion"
  refresh_time: 43200

Server:
  port: 8081
  host: "127.0.0.1"
  environment: "development"
  service_name: "chat-lion"
  read_timeout: 60
  write_timeout: 60

Redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10

Log:
  level: "info"
  file_path: "logs"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true
