# 开发环境配置
mysql:
  dsn: "root:0220059cyCY@tcp(localhost:3306)/lionchat?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10

jwt:
  signing_key: "chat-dev-key"
  expires_time: 604800
  buffer_time: 86400
  issuer: "chat"

server:
  port: 80
  mode: "debug"
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:8081"
    - "http://127.0.0.1:8081"
    - "http://localhost:8081"

log:
  level: "debug"
  format: "console"
  output: "stdout"
  file_path: "logs/chat.log"
  max_size: 100
  max_age: 30
  max_backups: 10
  compress: false

kafka:
  brokers:
    - "localhost:9092"
  topics:
    chat_messages: "chat-messages"
    user_events: "user-events"
    group_messages: "group-messages"
  consumer:
    group_id: "chat-consumer-group"
    auto_offset_reset: "latest"
  producer:
    acks: "all"
    retries: 3
    batch_size: 16384
    linger_ms: 1
    buffer_memory: 33554432