// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"chatLion/api/friend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/friend/addFriend",
				Handler: AddFriendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/friend/deleteFriend",
				Handler: DeleteFriendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/friend/getFriends",
				Handler: GetFriendsHandler(serverCtx),
			},
		},
	)
}
