// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: friend.proto

package friend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdderEmail    string                 `protobuf:"bytes,1,opt,name=adderEmail,proto3" json:"adderEmail,omitempty"`
	TargetEmail   string                 `protobuf:"bytes,2,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendRequest) Reset() {
	*x = AddFriendRequest{}
	mi := &file_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendRequest) ProtoMessage() {}

func (x *AddFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendRequest.ProtoReflect.Descriptor instead.
func (*AddFriendRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{0}
}

func (x *AddFriendRequest) GetAdderEmail() string {
	if x != nil {
		return x.AdderEmail
	}
	return ""
}

func (x *AddFriendRequest) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *AddFriendRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddMessage    string                 `protobuf:"bytes,1,opt,name=addMessage,proto3" json:"addMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendResponse) Reset() {
	*x = AddFriendResponse{}
	mi := &file_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendResponse) ProtoMessage() {}

func (x *AddFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendResponse.ProtoReflect.Descriptor instead.
func (*AddFriendResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{1}
}

func (x *AddFriendResponse) GetAddMessage() string {
	if x != nil {
		return x.AddMessage
	}
	return ""
}

type DeleteFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeleteEmail   string                 `protobuf:"bytes,1,opt,name=deleteEmail,proto3" json:"deleteEmail,omitempty"`
	TargetEmail   string                 `protobuf:"bytes,2,opt,name=targetEmail,proto3" json:"targetEmail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendRequest) Reset() {
	*x = DeleteFriendRequest{}
	mi := &file_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendRequest) ProtoMessage() {}

func (x *DeleteFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendRequest.ProtoReflect.Descriptor instead.
func (*DeleteFriendRequest) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFriendRequest) GetDeleteEmail() string {
	if x != nil {
		return x.DeleteEmail
	}
	return ""
}

func (x *DeleteFriendRequest) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

type DeleteFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeleteMessage string                 `protobuf:"bytes,1,opt,name=deleteMessage,proto3" json:"deleteMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendResponse) Reset() {
	*x = DeleteFriendResponse{}
	mi := &file_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendResponse) ProtoMessage() {}

func (x *DeleteFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendResponse.ProtoReflect.Descriptor instead.
func (*DeleteFriendResponse) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFriendResponse) GetDeleteMessage() string {
	if x != nil {
		return x.DeleteMessage
	}
	return ""
}

var File_friend_proto protoreflect.FileDescriptor

const file_friend_proto_rawDesc = "" +
	"\n" +
	"\ffriend.proto\x12\x06friend\"n\n" +
	"\x10AddFriendRequest\x12\x1e\n" +
	"\n" +
	"adderEmail\x18\x01 \x01(\tR\n" +
	"adderEmail\x12 \n" +
	"\vtargetEmail\x18\x02 \x01(\tR\vtargetEmail\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"3\n" +
	"\x11AddFriendResponse\x12\x1e\n" +
	"\n" +
	"addMessage\x18\x01 \x01(\tR\n" +
	"addMessage\"Y\n" +
	"\x13DeleteFriendRequest\x12 \n" +
	"\vdeleteEmail\x18\x01 \x01(\tR\vdeleteEmail\x12 \n" +
	"\vtargetEmail\x18\x02 \x01(\tR\vtargetEmail\"<\n" +
	"\x14DeleteFriendResponse\x12$\n" +
	"\rdeleteMessage\x18\x01 \x01(\tR\rdeleteMessage2\x95\x01\n" +
	"\x06Friend\x12@\n" +
	"\tAddFriend\x12\x18.friend.AddFriendRequest\x1a\x19.friend.AddFriendResponse\x12I\n" +
	"\fDeleteFriend\x12\x1b.friend.DeleteFriendRequest\x1a\x1c.friend.DeleteFriendResponseB\n" +
	"Z\b./friendb\x06proto3"

var (
	file_friend_proto_rawDescOnce sync.Once
	file_friend_proto_rawDescData []byte
)

func file_friend_proto_rawDescGZIP() []byte {
	file_friend_proto_rawDescOnce.Do(func() {
		file_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friend_proto_rawDesc), len(file_friend_proto_rawDesc)))
	})
	return file_friend_proto_rawDescData
}

var file_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_friend_proto_goTypes = []any{
	(*AddFriendRequest)(nil),     // 0: friend.AddFriendRequest
	(*AddFriendResponse)(nil),    // 1: friend.AddFriendResponse
	(*DeleteFriendRequest)(nil),  // 2: friend.DeleteFriendRequest
	(*DeleteFriendResponse)(nil), // 3: friend.DeleteFriendResponse
}
var file_friend_proto_depIdxs = []int32{
	0, // 0: friend.Friend.AddFriend:input_type -> friend.AddFriendRequest
	2, // 1: friend.Friend.DeleteFriend:input_type -> friend.DeleteFriendRequest
	1, // 2: friend.Friend.AddFriend:output_type -> friend.AddFriendResponse
	3, // 3: friend.Friend.DeleteFriend:output_type -> friend.DeleteFriendResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_friend_proto_init() }
func file_friend_proto_init() {
	if File_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friend_proto_rawDesc), len(file_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friend_proto_goTypes,
		DependencyIndexes: file_friend_proto_depIdxs,
		MessageInfos:      file_friend_proto_msgTypes,
	}.Build()
	File_friend_proto = out.File
	file_friend_proto_goTypes = nil
	file_friend_proto_depIdxs = nil
}
