// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModifyUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Email           string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	NewUserNickname string                 `protobuf:"bytes,2,opt,name=new_user_nickname,json=newUserNickname,proto3" json:"new_user_nickname,omitempty"` // 用户昵称
	NewUserGender   string                 `protobuf:"bytes,3,opt,name=new_user_gender,json=newUserGender,proto3" json:"new_user_gender,omitempty"`       // 用户性别
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModifyUserRequest) Reset() {
	*x = ModifyUserRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserRequest) ProtoMessage() {}

func (x *ModifyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserRequest.ProtoReflect.Descriptor instead.
func (*ModifyUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *ModifyUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ModifyUserRequest) GetNewUserNickname() string {
	if x != nil {
		return x.NewUserNickname
	}
	return ""
}

func (x *ModifyUserRequest) GetNewUserGender() string {
	if x != nil {
		return x.NewUserGender
	}
	return ""
}

type ModifyUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModifyMessage string                 `protobuf:"bytes,1,opt,name=modifyMessage,proto3" json:"modifyMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyUserResponse) Reset() {
	*x = ModifyUserResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserResponse) ProtoMessage() {}

func (x *ModifyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserResponse.ProtoReflect.Descriptor instead.
func (*ModifyUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *ModifyUserResponse) GetModifyMessage() string {
	if x != nil {
		return x.ModifyMessage
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"}\n" +
	"\x11ModifyUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12*\n" +
	"\x11new_user_nickname\x18\x02 \x01(\tR\x0fnewUserNickname\x12&\n" +
	"\x0fnew_user_gender\x18\x03 \x01(\tR\rnewUserGender\":\n" +
	"\x12ModifyUserResponse\x12$\n" +
	"\rmodifyMessage\x18\x01 \x01(\tR\rmodifyMessage2G\n" +
	"\x04User\x12?\n" +
	"\n" +
	"ModifyUser\x12\x17.user.ModifyUserRequest\x1a\x18.user.ModifyUserResponseB\bZ\x06./userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_proto_goTypes = []any{
	(*ModifyUserRequest)(nil),  // 0: user.ModifyUserRequest
	(*ModifyUserResponse)(nil), // 1: user.ModifyUserResponse
}
var file_user_proto_depIdxs = []int32{
	0, // 0: user.User.ModifyUser:input_type -> user.ModifyUserRequest
	1, // 1: user.User.ModifyUser:output_type -> user.ModifyUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
